### ISSUE TITLE
How to install probe

### ISSUE THREAD

**Issue by papiche** [artiommocrenco/meshtastic-prometheus-exporter#44]
I am a new meshtastic fan.
Looking for a way to monitor nodes, i found your project.

Can it be used on a computer through USB serial connection to "Heltec v3" ?
Does it need MQTT server relay ?

Could you give detail on how you use it ?

**Comment by artiommocrenco** [comment]
I've updated the [README](https://github.com/artiommocrenco/meshtastic-prometheus-exporter/blob/main/README.md), I hope it now provides better guidance now on how to use the project.

I've also created an issue to track serial connection as planned feature https://github.com/artiommocrenco/meshtastic-prometheus-exporter/issues/51 

Thanks, you're welcome to ask more questions should you need some more help.
