### ISSUE TITLE
Id like to use this with home assistant

### ISSUE THREAD

**Issue by valzzu** [artiommocrenco/meshtastic-prometheus-exporter#78]
Hi,

I'm running home assistant os so I can't use the normal ways of running this.

also I do have grafana already installed so id like to use that.

How could I get it running there? I did install Portainer to see if I could use it to run it, but I haven't found a way yet.

any info on how id do this?
thx!

**Comment by artiommocrenco** [comment]
Hello, this sounds like a home assistant question/limitation.

I can't help you with this
